travis:
  secure:
    BINSTAR_TOKEN: ND00r9wpcys25csBje99mcd3Ecm+zmdEapajc7+IEqn0y4+M8OZS83/j04cxt23wh73UR58ebD9qmFhqX4kOVNYShqimUQGGcrT3sGXiNa9c4B+hTEsSbSTVD/v4h83C06AVfzETTVXgiZlezCDGP21koZbhyEZEtBxZjCHMAkcii0llJML9a/ah90c6VRxjnUyMkV/mT12zcxp+3cfwAtUHlZgoClh1hJKAvNP/8mxsKWvOj5lYpPPMF1hkwRkuElTeQIn9C/up57gxhAkfm2x2tu/9wehjTfqhxqEwCEbo08jnDdn81ZK3Tj8MEvNXq0D8p45F5R/VxuvLV+c48cNKY45/jOfQ3hDaIvAb/9tuVBQx60Cr+bDl6KN+CCcp02JD9MxG9RW88nCFITEhS/+P2qYVHUYfDNmc/741ne3BqDz9YiuQWm9MFahzK65ng7CbR9SbFb0h0qaTCjT/0xT7IRhwzEj9ZHAYtk2DGEfOWIBW5eP57TLbY3bw2IeuEWcAZC2LGxO+cKLw9InuZnGa+04LeAeVFLm7gFPBGa2MhI7PimSTmBRbIvTurkvsKFYA57dBEhS6oA2wKRMVsd/gc04tV094h1EmpK/skLFWwA2gIGO5Y+2T9ST30sH7d6CQCFkuJR8VTPOHc2F6tKh3h0lqUyAxscivxmKGGO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
