travis:
  secure:
    BINSTAR_TOKEN: sq+iq7n/rUBsQGdWrCKJhAKDBH7viFtV50Cg7VE1HAZoKj3ZzmswkX/UQ2/PXoGNQKG2434PmwWUSRQs0SmcWXG1UwhxarVaTIQ+UOodkRZZ/re1V/32lude+qMRKMezEm999rGfGoMCEa/8KzxgR488L4xqt9qd2ASL4pPQATdtItxQG0UFW9dgRA59U+G5uDd62f+eqzrUl1MNt5t2PypnL3kH/rEfbp/WpMObOhc/uzstZqo8dfR9UVJ54frnN/b5AJixaNVVtnoKki3g8RMPawQtYMqR9aignyiPp+Z4u8R85nbrGFTOZTy92C1wangHoTb0b1kEfNjog1ubyDK2vWEgcqOoD3mAS78yI1Y1SO7haqs4Ui5rQ85Cu9R7Yt37go9d1XSdNSFxoxEz+FHHDylZP14me1N2FSZ6mzheP7p+5vmnWzi/Am8Tvy++PDdminmP1+EeQSH6WKBD4gUL1Gd/6A3XJw+7D7M+BO6hqLVXTkuRZa89wAjlKjf7N3w+gUFPjSLv0DNit4Y42OJrEERCc0UoaFOy5jJJD+WKRno8Vg0HGc/RZyKfG4y7Y6xCJJv7qO8nE453YhGnbL4fMZ1Ch5lnVoreOw2tNFr1OTs6C07Cvhu9bx7VGn5sCOoKzLQMxrxJueaLVhMZIKZzPy4U1qj45kYJDZhwHXU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
